version: '3.0'

services:
  simplebanking:
    image: postgres:12
    container_name: simplebanking
    restart: always
    ports:
      - "5434:5434"
    expose:
      - "5434"
    command: -p 5434
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: simplebankingDb
    volumes:
      - simplebanking-db:/var/lib/postgresql/data

volumes:
  simplebanking-db:
